name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: andyexeter/setup-bun@f5c5efee5778b44fb74ffe8a18e7c071d6057f55
        with:
          bun-version: '1.0.26'

      - name: Install frontend dependencies
        run: bun install --frozen-lockfile
